<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>VA.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="13.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\VA.Domain\VA.Domain.csproj" />
      <ProjectReference Include="..\VA.Infrastructure\VA.Infrastructure.csproj" />
    </ItemGroup>

</Project>
